name: Deploy Azure Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Key Vault
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment group create \
            --resource-group BCSAI2024-DEVOPS-STUDENTS-B-DEV \
            --template-file modules/key-vault.bicep \
            --parameters name=${{ vars.KEY_VAULT_NAME }} location=westeurope

    - name: Deploy Main Infrastructure
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment group create \
            --resource-group BCSAI2024-DEVOPS-STUDENTS-B-DEV \
            --template-file main.bicep \
            --parameters @parameters.json keyVaultName=${{ vars.KEY_VAULT_NAME }}

    - name: Get ACR credentials from Key Vault
      uses: azure/CLI@v1
      with:
        inlineScript: |
          ACR_USERNAME=$(az keyvault secret show --name acrUsername --vault-name ${{ vars.KEY_VAULT_NAME }} --query value -o tsv)
          ACR_PASSWORD=$(az keyvault secret show --name acrPassword --vault-name ${{ vars.KEY_VAULT_NAME }} --query value -o tsv)
          echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV

            